apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: astra-scheduler
    plugins:
      preFilter:
        enabled:
          - name: AstraScheduler
      filter:
        enabled:
          - name: AstraScheduler
      preScore:
        enabled:
          - name: AstraScheduler
      score:
        enabled:
          - name: AstraScheduler
      reserve:
        enabled:
          - name: AstraScheduler
