//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AINodeResourceProfile) DeepCopyInto(out *AINodeResourceProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AINodeResourceProfile.
func (in *AINodeResourceProfile) DeepCopy() *AINodeResourceProfile {
	if in == nil {
		return nil
	}
	out := new(AINodeResourceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AINodeResourceProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AINodeResourceProfileList) DeepCopyInto(out *AINodeResourceProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AINodeResourceProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AINodeResourceProfileList.
func (in *AINodeResourceProfileList) DeepCopy() *AINodeResourceProfileList {
	if in == nil {
		return nil
	}
	out := new(AINodeResourceProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AINodeResourceProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AINodeResourceProfileSpec) DeepCopyInto(out *AINodeResourceProfileSpec) {
	*out = *in
	if in.GPUs != nil {
		in, out := &in.GPUs, &out.GPUs
		*out = make([]GPUDeviceSpec, len(*in))
		copy(*out, *in)
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(RuntimeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = new(NodeCapabilities)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AINodeResourceProfileSpec.
func (in *AINodeResourceProfileSpec) DeepCopy() *AINodeResourceProfileSpec {
	if in == nil {
		return nil
	}
	out := new(AINodeResourceProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AINodeResourceProfileStatus) DeepCopyInto(out *AINodeResourceProfileStatus) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	if in.GPUs != nil {
		in, out := &in.GPUs, &out.GPUs
		*out = make([]GPUDeviceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Allocatable != nil {
		in, out := &in.Allocatable, &out.Allocatable
		*out = new(ResourceSummary)
		**out = **in
	}
	if in.Allocated != nil {
		in, out := &in.Allocated, &out.Allocated
		*out = new(ResourceSummary)
		**out = **in
	}
	if in.Available != nil {
		in, out := &in.Available, &out.Available
		*out = new(ResourceSummary)
		**out = **in
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(RuntimeStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Allocations != nil {
		in, out := &in.Allocations, &out.Allocations
		*out = make([]NodeAllocationStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AINodeResourceProfileStatus.
func (in *AINodeResourceProfileStatus) DeepCopy() *AINodeResourceProfileStatus {
	if in == nil {
		return nil
	}
	out := new(AINodeResourceProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIResourceAllocation) DeepCopyInto(out *AIResourceAllocation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIResourceAllocation.
func (in *AIResourceAllocation) DeepCopy() *AIResourceAllocation {
	if in == nil {
		return nil
	}
	out := new(AIResourceAllocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIResourceAllocation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIResourceAllocationList) DeepCopyInto(out *AIResourceAllocationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIResourceAllocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIResourceAllocationList.
func (in *AIResourceAllocationList) DeepCopy() *AIResourceAllocationList {
	if in == nil {
		return nil
	}
	out := new(AIResourceAllocationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIResourceAllocationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIResourceAllocationSpec) DeepCopyInto(out *AIResourceAllocationSpec) {
	*out = *in
	out.WorkloadRef = in.WorkloadRef
	if in.AssignedGPU != nil {
		in, out := &in.AssignedGPU, &out.AssignedGPU
		*out = new(AssignedGPU)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceSummary)
		**out = **in
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = new(AllocationActions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIResourceAllocationSpec.
func (in *AIResourceAllocationSpec) DeepCopy() *AIResourceAllocationSpec {
	if in == nil {
		return nil
	}
	out := new(AIResourceAllocationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIResourceAllocationStatus) DeepCopyInto(out *AIResourceAllocationStatus) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	if in.AppliedAt != nil {
		in, out := &in.AppliedAt, &out.AppliedAt
		*out = (*in).DeepCopy()
	}
	if in.ObservedResources != nil {
		in, out := &in.ObservedResources, &out.ObservedResources
		*out = new(ResourceSummary)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIResourceAllocationStatus.
func (in *AIResourceAllocationStatus) DeepCopy() *AIResourceAllocationStatus {
	if in == nil {
		return nil
	}
	out := new(AIResourceAllocationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIWorkloadProfile) DeepCopyInto(out *AIWorkloadProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIWorkloadProfile.
func (in *AIWorkloadProfile) DeepCopy() *AIWorkloadProfile {
	if in == nil {
		return nil
	}
	out := new(AIWorkloadProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIWorkloadProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIWorkloadProfileList) DeepCopyInto(out *AIWorkloadProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIWorkloadProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIWorkloadProfileList.
func (in *AIWorkloadProfileList) DeepCopy() *AIWorkloadProfileList {
	if in == nil {
		return nil
	}
	out := new(AIWorkloadProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIWorkloadProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIWorkloadProfileSpec) DeepCopyInto(out *AIWorkloadProfileSpec) {
	*out = *in
	out.WorkloadRef = in.WorkloadRef
	if in.TimeWindows != nil {
		in, out := &in.TimeWindows, &out.TimeWindows
		*out = make([]TimeWindow, len(*in))
		copy(*out, *in)
	}
	if in.SLO != nil {
		in, out := &in.SLO, &out.SLO
		*out = new(WorkloadSLO)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(WorkloadResourceRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(WorkloadPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIWorkloadProfileSpec.
func (in *AIWorkloadProfileSpec) DeepCopy() *AIWorkloadProfileSpec {
	if in == nil {
		return nil
	}
	out := new(AIWorkloadProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIWorkloadProfileStatus) DeepCopyInto(out *AIWorkloadProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIWorkloadProfileStatus.
func (in *AIWorkloadProfileStatus) DeepCopy() *AIWorkloadProfileStatus {
	if in == nil {
		return nil
	}
	out := new(AIWorkloadProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllocationActions) DeepCopyInto(out *AllocationActions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocationActions.
func (in *AllocationActions) DeepCopy() *AllocationActions {
	if in == nil {
		return nil
	}
	out := new(AllocationActions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllocationRef) DeepCopyInto(out *AllocationRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocationRef.
func (in *AllocationRef) DeepCopy() *AllocationRef {
	if in == nil {
		return nil
	}
	out := new(AllocationRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssignedGPU) DeepCopyInto(out *AssignedGPU) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssignedGPU.
func (in *AssignedGPU) DeepCopy() *AssignedGPU {
	if in == nil {
		return nil
	}
	out := new(AssignedGPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUDeviceSpec) DeepCopyInto(out *GPUDeviceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUDeviceSpec.
func (in *GPUDeviceSpec) DeepCopy() *GPUDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(GPUDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUDeviceStatus) DeepCopyInto(out *GPUDeviceStatus) {
	*out = *in
	if in.AllocatedTo != nil {
		in, out := &in.AllocatedTo, &out.AllocatedTo
		*out = new(AllocationRef)
		**out = **in
	}
	if in.MIGSlices != nil {
		in, out := &in.MIGSlices, &out.MIGSlices
		*out = make([]MIGSliceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUDeviceStatus.
func (in *GPUDeviceStatus) DeepCopy() *GPUDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(GPUDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesObjectRef) DeepCopyInto(out *KubernetesObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesObjectRef.
func (in *KubernetesObjectRef) DeepCopy() *KubernetesObjectRef {
	if in == nil {
		return nil
	}
	out := new(KubernetesObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MIGSliceStatus) DeepCopyInto(out *MIGSliceStatus) {
	*out = *in
	if in.AllocatedTo != nil {
		in, out := &in.AllocatedTo, &out.AllocatedTo
		*out = new(AllocationRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MIGSliceStatus.
func (in *MIGSliceStatus) DeepCopy() *MIGSliceStatus {
	if in == nil {
		return nil
	}
	out := new(MIGSliceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAllocationStatus) DeepCopyInto(out *NodeAllocationStatus) {
	*out = *in
	if in.AssignedGPU != nil {
		in, out := &in.AssignedGPU, &out.AssignedGPU
		*out = new(AssignedGPU)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceSummary)
		**out = **in
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = new(AllocationActions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAllocationStatus.
func (in *NodeAllocationStatus) DeepCopy() *NodeAllocationStatus {
	if in == nil {
		return nil
	}
	out := new(NodeAllocationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeCapabilities) DeepCopyInto(out *NodeCapabilities) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeCapabilities.
func (in *NodeCapabilities) DeepCopy() *NodeCapabilities {
	if in == nil {
		return nil
	}
	out := new(NodeCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSummary) DeepCopyInto(out *ResourceSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSummary.
func (in *ResourceSummary) DeepCopy() *ResourceSummary {
	if in == nil {
		return nil
	}
	out := new(ResourceSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeCapacity) DeepCopyInto(out *RuntimeCapacity) {
	*out = *in
	if in.TokenThroughput != nil {
		in, out := &in.TokenThroughput, &out.TokenThroughput
		*out = new(TokenThroughput)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeCapacity.
func (in *RuntimeCapacity) DeepCopy() *RuntimeCapacity {
	if in == nil {
		return nil
	}
	out := new(RuntimeCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimePressure) DeepCopyInto(out *RuntimePressure) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimePressure.
func (in *RuntimePressure) DeepCopy() *RuntimePressure {
	if in == nil {
		return nil
	}
	out := new(RuntimePressure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeSpec) DeepCopyInto(out *RuntimeSpec) {
	*out = *in
	if in.Supports != nil {
		in, out := &in.Supports, &out.Supports
		*out = new(RuntimeSupports)
		**out = **in
	}
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(RuntimeCapacity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeSpec.
func (in *RuntimeSpec) DeepCopy() *RuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeStatus) DeepCopyInto(out *RuntimeStatus) {
	*out = *in
	if in.Pressure != nil {
		in, out := &in.Pressure, &out.Pressure
		*out = new(RuntimePressure)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeStatus.
func (in *RuntimeStatus) DeepCopy() *RuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(RuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeSupports) DeepCopyInto(out *RuntimeSupports) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeSupports.
func (in *RuntimeSupports) DeepCopy() *RuntimeSupports {
	if in == nil {
		return nil
	}
	out := new(RuntimeSupports)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeWindow) DeepCopyInto(out *TimeWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeWindow.
func (in *TimeWindow) DeepCopy() *TimeWindow {
	if in == nil {
		return nil
	}
	out := new(TimeWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenThroughput) DeepCopyInto(out *TokenThroughput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenThroughput.
func (in *TokenThroughput) DeepCopy() *TokenThroughput {
	if in == nil {
		return nil
	}
	out := new(TokenThroughput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPolicy) DeepCopyInto(out *WorkloadPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPolicy.
func (in *WorkloadPolicy) DeepCopy() *WorkloadPolicy {
	if in == nil {
		return nil
	}
	out := new(WorkloadPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadResourceRequest) DeepCopyInto(out *WorkloadResourceRequest) {
	*out = *in
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(ResourceSummary)
		**out = **in
	}
	if in.Preferred != nil {
		in, out := &in.Preferred, &out.Preferred
		*out = new(ResourceSummary)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadResourceRequest.
func (in *WorkloadResourceRequest) DeepCopy() *WorkloadResourceRequest {
	if in == nil {
		return nil
	}
	out := new(WorkloadResourceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSLO) DeepCopyInto(out *WorkloadSLO) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSLO.
func (in *WorkloadSLO) DeepCopy() *WorkloadSLO {
	if in == nil {
		return nil
	}
	out := new(WorkloadSLO)
	in.DeepCopyInto(out)
	return out
}
